spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://192.168.0.111:5432/bootify}
    username: ${JDBC_DATABASE_USERNAME:myuser}
    password: ${JDBC_DATABASE_PASSWORD:password}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
    resources.cache-period: 0
    thymeleaf.cache: false
    devtools.livereload.enabled: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
springdoc:
  pathsToMatch: /api/**

# spring.devtools.livereload.enabled=false

# Templates reloading during development
# spring.thymeleaf.prefix=${project.base-dir}/src/main/resources/templates/
# spring.thymeleaf.cache=false

# Static resources reloading during development
# spring.resources.static-locations=${project.base-dir}/src/main/resources/static/
# spring.resources.cache-period=0