spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${JDBC_DATABASE_USERNAME:myuser}
    password: ${JDBC_DATABASE_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 250
    
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.id.new_generator_mappings: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
  web:
    # Static resources reloading during development
    # resources.static-locations=${project.base-dir}/src/main/resources/static/
    resources.cache.period: 0
  thymeleaf:
    # prefix: ${project.base-dir}/src/main/resources/templates/
    cache: false
  devtools.livereload.enabled: false
springdoc:
  pathsToMatch: /api/**
logging.level:
  org.hibernate.SQL: DEBUG
  org.hibernate.type: TRACE
  org.hibernate: ERROR
  org.springframework.web: DEBUG
